name: openSUSE Tumbleweed NVIDIA Driver Validator
on:
  workflow_dispatch:

jobs:
  run-validator:
    environment: nvidia-validator
    env:
      DOCKER_IMAGE: "opensuse/tumbleweed:latest"
    if: ${{ github.repository_owner == 'xuzhao9' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: workspace
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout Tumbleweed docker snapshot
        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
        with:
          docker-image: ${{ env.DOCKER_IMAGE }}
      - name: Run Tumbleweed docker
        run: |
          container_id=$(docker run \
            --tty \
            --detach \
            -v "${PWD}/workspace:/workspace" \
            -w / \
            "${{ env.DOCKER_IMAGE }}" \
            tail -f /dev/null
          )
          echo "container_id=${container_id}" >> $GITHUB_ENV
      - name: Run the validator
        run: |
          echo "Container ID: ${container_id}"
          docker exec -t -w "/workspace" "${container_name}" bash /workspace/.github/scripts/metadata.sh
          docker exec -t -w "/workspace" "${container_name}" bash /workspace/.github/scripts/build.sh
      - name: Upload the result to GitHub Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Validator Result
          path: workspace/.workdir/build
      - name: Kill all running Tumbleweed dockers
        if: always()
        run: |
          docker kill $(docker ps -q)
